export const siteConfig = {
  name: "Basic Cremation",
  domain: "basiccremation.co.uk",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://basiccremation.co.uk",
  phone: process.env.NEXT_PUBLIC_PHONE || "0333 242 1405",
  phoneTel: (process.env.NEXT_PUBLIC_PHONE || "0333 242 1405").replace(/\s/g, ""),
  description:
    "Information and arrangement help for families needing a basic cremation in England, Scotland and Wales. Available 24 hours a day.",
  basePrice: 1499,
  priorityCarePrice: 250,
  // The Tier 1 location set used in nav, sitemap, and location index pages
  tier1Locations: [
    "london",
    "birmingham",
    "manchester",
    "leeds",
    "liverpool",
    "sheffield",
    "bristol",
    "newcastle",
    "nottingham",
    "leicester",
    "coventry",
    "reading",
    "brighton",
    "bolton",
    "sunderland",
    "southampton",
    "hull",
    "plymouth",
    "milton-keynes",
    "wolverhampton",
    "derby",
    "stoke-on-trent",
    "northampton",
    "luton",
    "swindon",
    "norwich",
    "york",
    "portsmouth",
    "peterborough",
    "bournemouth",
    "southend",
    "oxford",
    "cambridge"
  ]
};
